packages:
  - "packages/dev-server"
  - "packages/init"
  - "packages/repack"
  - "apps/tester-app"
  - "apps/tester-federation"
  - "apps/tester-federation-v2"
  - "tests/metro-compat"
  - "website"
