packages:
  - "packages/dev-server"
  - "packages/repack"
  - "packages/TesterApp"
  - "packages/debugger-app"
  - "packages/init"
  - "website"
  - "metro-compat-test"
  - "examples/with-zephyr/*"

catalog:
  "react": "18.2.0"
  "react-native": "0.74.3"
  # babel
  "@babel/cli": "^7.23.9"
  "@babel/core": "^7.23.9"
  "@babel/preset-env": "^7.23.9"
  "@babel/preset-typescript": "^7.23.3"
  "@babel/runtime": "^7.23.9"
  # swc
  "@swc/helpers": "^0.5.12"
  # rspack
  "@rspack/core": "1.0.0-alpha.5"
  "@rspack/plugin-react-refresh": "1.0.0-alpha.5"
  # bin
  "eslint": "^8.57.0"
  "prettier": "^3.2.4"
  "typescript": "^5.5.3"
  # types
  "@types/jest": "^29.5.12"
  "@types/react": "^18.2.6"

catalogs:
  examples:
    "react": "18.2.0"
    "react-native": "0.74.3"
    # deps
    "@react-native-masked-view/masked-view": "^0.3.1"
    "@react-navigation/native": "^6.1.18"
    "@react-navigation/native-stack": "^6.10.1"
    "react-native-safe-area-context": "^4.10.8"
    "react-native-screens": "^3.32.0"
    # RN dev
    "@react-native/babel-preset": "0.74.83"
    "@react-native/eslint-config": "0.74.83"
    "@react-native/typescript-config": "0.74.83"
