name: Deploy PR

on:
  pull_request:
  workflow_dispatch:

jobs:
  preview_website:
    runs-on: ubuntu-latest

    # Skip running on forks since it won't have access to secrets
    if: >
      github.event_name == 'workflow_dispatch' || 
      github.event.pull_request.head.repo.full_name == github.repository

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v3

      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Deploy website
        uses: ./.github/actions/deploy-website
        with:
          netlify-auth-token: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          netlify-site-id: ${{ secrets.NETLIFY_SITE_ID }}
