name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  verify:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node_version: ['12', '14']
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v2
      
      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node_version }}

      - name: Install dependencies
        run: npm i

      - name: Lint
        run: npm run lint
        
      - name: Type check
        run: npm run tsc
        
      - name: Run tests
        run: npm run test
        
      - name: Verify client dashboard builds
        run: npm run webpack

  preview_website:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Use Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Install dependencies
        run: npm i

      - name: Build & export website
        working-directory: website
        run: npm run build && npm run export

      - name: Deploy website in preview mode
        working-directory: website
        run: npx netlify deploy --dir=out
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}